### ISSUE TITLE
Not full info in the Invoices

### ISSUE THREAD

**Issue by VPopDiceus** [XeroAPI/xero-node#150]
Hello!
In the account we see invoice with ListItems
![2018-01-16 16 19 12](https://user-images.githubusercontent.com/35494990/34994001-dd9683bc-fada-11e7-9cd0-b74ce4e0a03f.png)
In the preview too exists ListeItems
![2018-01-16 16 20 03](https://user-images.githubusercontent.com/35494990/34994026-f1fa2426-fada-11e7-910b-aa115c3d4df7.png)
But then get with `xeroClient.core.invoices.getInvoices()` this invoice has empty ListItems
![2018-01-16 16 21 09](https://user-images.githubusercontent.com/35494990/34994085-16dde980-fadb-11e7-8bad-5b2760a58d95.png)

**Comment by JamesColemanXero** [comment]
Hi, this is likely to because in the API Previewer you are providing the InvoiceId, whereas in the getInoices() method you are getting all of your invoices. The difference is that the Xero API will return a trimmed down results set if you obtain all invoices, if you specify an individual invoice, or use paging, the full details will be returned. More info on this [here](https://developer.xero.com/documentation/api/requests-and-responses).

**Comment by VPopDiceus** [comment]
Thanks @JamesColemanXero! 
Solved with GET by `InvoiceID`
