### ISSUE TITLE
End-to-end tests reach rate limit

### ISSUE THREAD

**Issue by philals** [XeroAPI/xero-node#207]
At the moment adding any more end to end tests will reach Xero API's rate limit.

**Comment by adamreisnz** [comment]
Since the rate limit is 60 requests per minute for a given organisation, a simple way to get around this would be to let the script pause for a bit between each request. Depending on how many requests there are in the test, it might be sufficient to pause for half a second between each request, but to be safe it can be extended to one full second.

If using the bluebird promise library, this can easily be achieved using:

```js
await this.xero.doSomeRequest();
await Promise.delay(1000);
```

We use the same approach in our app when making multiple calls to avoid hitting the (low) rate limit.

**Comment by philals** [comment]
Cheers @adamreisnz,

This is likely going to be our next course. 

We were hesitant to add a delay(), and managed to get by using two Private apps. However the extra overhead that gives people wanting to run the tests is a bit much.

Next time we're adding more tests we'll swap to a delay() strategy.

Marking this a good first issue for anyone keen to get involved.
