### ISSUE TITLE
Improved documentation for Journals offset/modified after

### ISSUE THREAD

**Issue by stunt-pilot** [XeroAPI/xero-node#269]
Hi there folks,

This isn't an issue as much as a request that examples be included in the documentation. I spent a fair bit of time working out how the offset parameter works (along with the Date format) for Journals. 

* journals.get() will return up to 100 records, 

* journals.get( offset: i ) request the next up to 100 records starting from the JournalNumber of the last journal returned (see example below)

* journals.get( 'If-Modified-Since': after ); after is a date that is in ISO format without the milliseconds (see example below)

* the 'If-Modified-Since' parameter returns journals that have a creation date (CreatedDateUTC) after that time, not the journal date (JournalDate)

```
function getJournalEntries( transactionOffset, after ) 
{
        return self.currentApp.journals.get( { offset: transactionOffset, 'If-Modified-Since': after.toISOString().split('.')[0] }  )
            .then(function(response) 
{
                console.log("got [" + response.Journals.length + "] journal transactions " + JSON.stringify(response.Journals) );
                return response;
            })
            .catch(function(err) {
                console.log("get journal entries error : " + err);
            });
   }
}


function getJournalData( transactions, after ) {

        var offset = 0;
        if( transactions.Journals.length > 0 )
        {
            offset = transactions.Journals[transactions.Journals.length - 1].JournalNumber;
        }
        console.log("getJournalData journal data length : " + offset);
            
        return getJournalEntries( offset, after ).then(function(response) {
            console.log("got journal entry response : " + JSON.stringify(response));
            transactions.Journals.push.apply(transactions.Journals, response.Journals);
            if (response.Journals.length == 100 ) {
                // run the operation again
                return getJournalData( transactions, after );
            }
            else
            {
                return transactions;
            }
        });
    }
};
```
Correct me if I'm wrong on anything above. Thanks and I hope it helps someone out.

**Comment by stansv** [comment]
The official api docs (https://developer.xero.com/documentation/api/journals) are sometimes superficial, I can agree, but I wouldn't say it is useless. Everything you've noted looks correct, but that's all not an issue of node.js client, so maybe better to report this on forums (https://community.xero.com/?domain=developer) or https://github.com/XeroAPI/Api.Documentation repository, though it's not the repository where they maintain documentation sources.

If-Modified-Since is compared with either `CreatedDateUTC` or `UpdatedDateUTC`, i.e. technical timestamps, not business dates, depending on whether entity is immutable (like journals) or can be modified (like invoices).
