### ISSUE TITLE
XeroClient is not a constructor

### ISSUE THREAD

**Issue by philliplakis** [XeroAPI/xero-node#297]
**SDK you're using (please complete the following information):**
 - Version 4.0.2

**Describe the bug**

**To Reproduce**
1. Go to https://github.com/XeroAPI/xero-node-samples/blob/master/private_example.js
2. Fill out your config data.
3. run file

**Expected behavior**

I created a new App, I used the sample file above and filled my details but i can not run it.

**Comment by ezetaraborelli** [comment]
That example is for version 3.x.x, you can make a downgrade of the package if you want, although I'd recommend you start working with version 4.0.2, because it comes with support for oAuth 2.0, and oAuth 1.0 apps will be disabled soon. This is the branch you have to check https://github.com/XeroAPI/xero-node/tree/oauth2

**Comment by philliplakis** [comment]
Thanks for the reply and pointers. 
Interestingly i didn't download the beta tagged from npm. My oversight.
