### ISSUE TITLE
Breaking change to how errors are returned

### ISSUE THREAD

**Issue by blairjo** [XeroAPI/xero-node#324]
**SDK you're using (please complete the following information):**
 - Version [e.g. 4.0.6]

**Describe the bug**
On v3 when an error occurred in the call to Xero, say when creating an invoice, the promise was still resolved by xero-node andthe result would contain the Invoice, which would have a ValidationErrors property that could be checked. On v4 the promise is no longer returned, it is rejected, then I need to dig around in error.response.body.elements[0].ValidationErrors to see the error. 

**To Reproduce**
Call accountingApi.createInvoice with an invalid account code. The promise is rejected, and the Invoice is not serialized to an Invoice object

**Expected behavior**
The promise should resolve, with the body containing an Invoice item that has a collection of ValidationError objects, as per v3.

**Comment by SidneyAllen** [comment]
@blairjo - we released 4.1.0 which fixed createInvoices so you can pass the "summarizeError=false" param.  So, when creating multiple invoices you'll get back an array of invoices that includes both successfully created invoices (with ID) and any invoices along with validation errors.  This will be a status 200 OK response.

`


[// Array of Invoices needed
const newInvoices: Invoices = new Invoices()

// add an invoice with the same InvoiceNum twice
newInvoices.invoices = [invoice1, invoice1];

// CREATE ONE OR MORE INVOICES
const createdInvoice = await xero.accountingApi.createInvoices(req.session.activeTenant, newInvoices, false)

console.log(createdInvoice.response.statusCode);

// Since we are using summarizeErrors = false we get 200 OK statuscode
// Our array of created invoices include those that succeeded and those with validation errors.
// loop over the invoices and if it has an error, loop over the error messages
for(let i=0; i<createdInvoice.body.invoices.length; i++){
    if(createdInvoice.body.invoices[i].hasErrors) {
        let errors = createdInvoice.body.invoices[i].validationErrors;
        for(let j=0; j<errors.length; j++){
          console.log(errors[j].message);
        }
    }
}
`
