### ISSUE TITLE
Is there any documentation ?

### ISSUE THREAD

**Issue by ajouve** [XeroAPI/xero-node#340]
Hi,

We have some code using private Xero applications.

We will have to change it because this solution is deprecated

We are having a look to the code but the migration seems complicated.

First there is no way to have a full backend management we will have to include an OAuth2. 

Another problem is that we can not found any API documentation for this node module, is there any places the methods are listed ?

Las problem seems that public applications can not be connected with the test company, is there any way to have a free test account for our development ?

Thanks

**Comment by ajouve** [comment]
Any news ?

**Comment by SidneyAllen** [comment]
Hi @ajouve 

With the move from private app type on OAuth 1.0a you will need to refactor your integration to include an oauth 2 flow in order to obtain an access token and refresh token and persist them in a database.  Once you have those, you'll be able to connect to Xero's API.  Access tokens expire after 30min, so you will need to refresh tokens once they expire.

A "starter" typescript code is available that has an example of the oAuth 2.0 flow.
https://github.com/XeroAPI/xero-node-oauth2-ts-starter

You should still be able to use the free demo company that comes with every Xero user account. Please see our docs on this topic
https://developer.xero.com/documentation/getting-started/development-accounts

**Comment by SidneyAllen** [comment]
@ajouve - we've published additional documentation for xero-node v4 SDK https://xeroapi.github.io/xero-node/

**Comment by ajouve** [comment]
I have a 404

**Comment by SerKnight** [comment]
Sorry @ajouve - we updated to include the legacy docs as well - the link is `https://xeroapi.github.io/xero-node/v4`
