### ISSUE TITLE
Attachments content is undefined on PartnerApplication

### ISSUE THREAD

**Issue by ChrisGrigg** [XeroAPI/xero-node#37]
When I use the Public Application and invoke the following code:

    xeroClient.core.invoices.getInvoice(invoiceID)
            .then(function(invoice) {
                invoice.getAttachments()
                    .then(function(attachments) {
                        //Get the reference to the attachment object
                        var myAttachment = attachments[0];

                        //Create a local writestream
                        var wstream = fs.createWriteStream('temp.pdf', { defaultEncoding: 'binary' });

                        wstream.on('finish', function() {
                            //Data has been written successfully
                            res.send('done');
                        });

                        wstream.on('error', function(err) {
                            console.log('data writing failed',err);
                            wstream.close();
                        });

                        myAttachment.getContent(wstream)
                            .catch(function(err) {
                                console.log('Some error occurred: ', err);
                    });
            });

Everything works fine and the invoice's attachment is written locally.

However when I upgrade to a Partner Application. The file is empty. It's strange because I can log the file size and that is correct, it's just the actual file that is empty.

Maybe I'm missing something?

**Comment by jordanwalsh23** [comment]
No, you're not missing something.  This is indeed a bug.  The attachments are currently coming back with the protocol as `http` instead of `https`. 

This means that when you request the content it is returning a `302 Found`.  This seems to redirect fine when using public tokens, but when you're using partner it throws an error.

I'll release a patch soon, but if you want to work around it you can simply regex the protocol to https and it works e.g.

`attachment.Url = attachment.Url.replace(/http:/i, "https:");`

Thanks

**Comment by jordanwalsh23** [comment]
xero-node@2.1.6 published to npm that fixes this issue.
