### ISSUE TITLE
Unable to create invoice or quote. body: Invoices { invoices: undefined }

### ISSUE THREAD

**Issue by DevJHansen** [XeroAPI/xero-node#399]
**SDK you're using (please complete the following information):**
 - Version 4.4.3

Hey guys, I'm unable to create quotes or invoices and keep getting a "Server Error". In my console I get something like this: body: Invoices { invoices: undefined }. Not sure what the issue might be here, but I am able to make other calls to your API without any issue. I can get get quotes, invoices, items, contacts etc no problem but for the life of me I can't get this to work. 

Here is my code (I believe I've done everything right): 
```
const Invoices = {
    invoices: [
      {
        type: "ACCREC",
        contact: {
          contactID: "0319be39-f949-4ae2-a0f4-868fece4ba8e"
        },
        lineItems: [
          {
            description: "Acme Tires",
            quantity: 2.0,
            unitAmount: 20.0,
            accountCode: "500",
            taxType: "NONE",
            lineAmount: 40.0
          }
        ],
        date: "2019-03-11",
        dueDate: "2018-12-10",
        reference: "Website Design",
        status: "AUTHORISED"
      }
    ]
  };

  await xero.accountingApi.createInvoices(tenantData[0].tenantId, Invoices);

```

**Comment by RettBehrens** [comment]
Hmm, I'm not able to replicate this using the latest version of the sdk, 4.4.8. Can you try updating your version? Here's the code I used to test with 4.4.8:

`const contacts = await xero.accountingApi.getContacts(req.session.activeTenant.tenantId);

		const invoices = {
			invoices: [
				{
					type: "ACCREC",
					contact: {
						contactID: contacts.body.contacts[0].contactID
					},
					lineItems: [
						{
							description: "Acme Tires",
							quantity: 2.0,
							unitAmount: 20.0,
							accountCode: "500",
							taxType: "NONE",
							lineAmount: 40.0
						}
					],
					date: "2019-03-11",
					dueDate: "2018-12-10",
					reference: "Website Design",
					status: "AUTHORISED"
				}
			]
		};

		const invoice = await xero.accountingApi.createInvoices(req.session.activeTenant.tenantId, invoices);`

**Comment by RettBehrens** [comment]
@DevJHansen If you have issues with 4.4.8 reopen this issue

**Comment by mcybulski** [comment]
I'm having trouble moving an invoice from status 'AUTHORIZED' to 'VOIDED'. I will also note that all payments on the invoice have been already removed. 

I'm using Xero-Node API version 4.5.1, and I'm also receiving a similar error in the console. 

`body: Invoices { invoices: undefined }`

I'm also receiving validation exception in the console, which I've been unable to understand the meaning of.

```
body: {
      ErrorNumber: 10,
      Type: 'ValidationException',
      Message: 'A validation exception occurred',
      Elements: [Array]
    }
```

Here's the code I'm trying to run to change the status of an invoice. In the below code, inv.invoiceID refers to an invoice object stored in MongoDB. The above error about undefined invoices is confusing, because in the below code, you can see I assign an 'Invoice' with a new status code and place into the 'Invoices' array.

```
let invoicesArray = new Invoices;
let invoice = new Invoice;
let voidedStatus = Invoice.StatusEnum.VOIDED;
invoice.status = voidedStatus; 
invoice.invoiceID = inv.invoiceID;
invoicesArray.invoices = [invoice];

const voidedInvoice = await xero.accountingApi.updateInvoice(
                    req.session.activeTenant.tenantId,
                    inv.invoiceID,
                    invoicesArray,
                    2
);

```
In the above code, the 'Invoices' object is required as a parameter to the updateInvoices function call with a single 'Invoice' object in its array. My assumption is that this new 'Invoice' object will contain the new attributes to overwrite in the real record stored in Xero for the InvoiceID passed into the function. 

I still don't understand why a custom object "Invoices" has to be passed into the updateInvoices function, as opposed to just the singular Invoice object I'm looking to update. It's very confusing and seemingly pointless that these pluralized objects have been created at all as types. 

I've used the above pattern successfully for the updateContacts call. So, it seems to be something directly related to the Invoices api call that I'm either not using properly, or is broken. For reference, here is that code that worked just fine to archive a contact. 

```
let contactsArray = new Contacts;
let contact = new Contact;
let status = Contact.ContactStatusEnum.ARCHIVED;
contact.contactStatus = status;
contactsArray.contacts = [contact];

 // Archive contact associated with invoice
const archivedContact = await xero.accountingApi.updateContact(
                  req.session.activeTenant.tenantId,
                  inv.contact.contactID,
                  contactsArray
);
```

You help to resolve would be greatly appreciated!
