### ISSUE TITLE
Documentation typo/needs updating: Refresh token expiry time

### ISSUE THREAD

**Issue by TaylorDale** [XeroAPI/xero-node#409]
The Readme.txt states the refresh token lasts for 30 days, whereas this ticket https://community.xero.com/developer/discussion/105714701 indicates it has been increased to 60 days. Is the latter correct? 

Please consider headless access to the Xero API's as the prospect of having to kickstart the auth manually if the refresh token ever expires is really frustrating.

**Comment by SerKnight** [comment]
Thanks Taylor - that was an increase of limits added a few months ago. Documentation updated

**Comment by SerKnight** [comment]
Also you might find this useful - i've created a video on how to manage a longstanding API connection since Private Apps are no more. I agree it would be idea to have a 'Headless' / infinite api connection - but since every api action is on behalf of a Xero User account, we decided to move towards a more secure approach to provisioning and maintaining API access.

https://www.youtube.com/watch?v=Zcf_64yreVI

**Comment by TaylorDale** [comment]
Hi Chris thanks for that video I've had a watch, looks like this will be the way we move forward with our integrations. Good to know about XOAuth too. All of our applications are "Super Admin" style so the user-facing access style elected for here doesn't quite fit but will make do. Would be great to see a Google service account equivalent be implemented but I won't hold out for it. Thanks again for the help.
