### ISSUE TITLE
Question: Is rate limiting implemented on the library level?

### ISSUE THREAD

**Issue by sandorvasas** [XeroAPI/xero-node#441]
Question: Is rate limiting implemented on the library level, and it'll throw an error or retry after the returned value of 'Retry-After' header, or do I need to wrap all xero-node api calls in a rate limit checker which reads the headers and manages calls based on them?

**Comment by SerKnight** [comment]
Exceeding a rate limit will result in an HTTP 429 (too many requests) response. It will include an X-Rate-Limit-Problem header telling you which limit you have reached.
> https://developer.xero.com/documentation/oauth2/limits

However we have discussed internally how to better support library (SDK) level rate limit support. Can you elaborate on the ideal feature scenario where the library would support you in managing the API limits other than the 429 response + headers?

**Comment by sandorvasas** [comment]
Thanks for your response. One possible library feature I can think of is defining a maxWaitTime & maxRetries when constructing the XeroClient, and when hitting the rate limit and the Retry-After header's value is smaller than the maxWaitTime, xero-node could block for a while, and retry the same API call. Until maxRetries or maxWaitTime is reached.  If any retries are needed, then maxWaitTime would be taken into account, so if the total time period of e.g 3 retries exceed maxWaitTime, it could also throw an error.
If any of them is reached, it could throw a MaxRetriesReachedError or a MaxWaitTimeReached error, so no raw HTTP header parsing is needed.

**Comment by SerKnight** [comment]
Thanks for the context. If this is something you have already implemented and we're able to share code snippets we can start thinking on what it might look like for this repo.

We don't want to assume any infrastructure (retries, bg job queues, etc..) for this repo but with some other discussion  there might be a solution that simplifies rate limiting for everyone.

**Comment by SerKnight** [comment]
![Screen Shot 2020-09-29 at 11 41 49 AM](https://user-images.githubusercontent.com/2935387/94595991-c4f19680-0248-11eb-8d4c-0b9068a00e43.png)

**Comment by lk9100** [comment]
> Thanks for the context. If this is something you have already implemented and we're able to share code snippets we can start thinking on what it might look like for this repo.
> 
> We don't want to assume any infrastructure (retries, bg job queues, etc..) but with some other discussion there might be a solution that simplifies rate limiting for everyone.

I agree with this.

IMO it'd be a bad idea to include rate limiting in this library, if an api call exceeds rate, it should just fail, and we should handle this in our project.

I do not think it's a super good idea to rely on 'Retry-After' header to implement rate limit on user side, that fact you are receiving 'Retry-After' header means the implementation is not in line with API spec, and when it happens, it should be considered as exception.

**Comment by gentlefox** [comment]
> IMO it'd be a bad idea to include rate limiting in this library, if an api call exceeds rate, it should just fail, and we should handle this in our project.
> 
> I do not think it's a super good idea to rely on 'Retry-After' header to implement rate limit on user side, that fact you are receiving 'Retry-After' header means the implementation is not in line with API spec, and when it happens, it should be considered as exception.

There are plenty of different rate limiting solutions as customisable modules that can be implemented by anyone using this module. Some are based on requests, while others rate limit method calls. I know there are ones that explicitly handle and manage every one of the specified limits defined above, with the added bonus of customisable 429 response handling eg: pause all requests for an absolute X minutes (5 minutes is fairly standard), or check for a retry-after header and use that value if it exists, otherwise initiates an internal call to resolve which of the limits was violated, such as for daily limit, and assigns midnight as time to resume.

TL;DR?
* valid modules already exist offering this functionality.
* end users should already be aware that "Retry-After" headers are a server courtesy that shouldn't be relied upon.
* and realistically, this module should be used for models / api endpoints etc, but they should create their own HTTP(S) client implementation, especially as *request* is outdated, has been deprecated for years, and presents a security vulnerability.

**Comment by SerKnight** [comment]
Hey all.

This has been a good thread. Thanks for all the thoughts and feedback.

At this point we won't be adding rate limiting to the project. I think most agree its an application dependent problem.

As for the request deprecation, it is something we will be moving off of in the near term. The client templates are weaved into a code generation OS project called openapi-codegen, so it is taking some time to ensure the migration to another request lib wont impact any active usage.

As for the project being only a model / api endpoint wrapper, I understand the sentiment, but we have a lot of developers and helping to facilitate the OAuth flow & request/response handling smoothly is a benefit of using an SDK.
