### ISSUE TITLE
Support for Workflow Max API's and XPM?

### ISSUE THREAD

**Issue by LiamTrioTech** [XeroAPI/xero-node#459]
Would like to authenticate and use the Workflow Max API's / XPM API's with this module.

For example: 
Staff, Costs, Invoices, Jobs, Quotes, Tasks and Time.
https://api.xero.com/workflowmax/3.0/staff.api/list

**Describe alternatives you've considered**
Implement as per documentation, leveraging what we can from Node.js Oauth SDK example.

**Additional context**
Xero Gateway, API V3 and OAuth 2 are required to use by end of year.
See: https://www.workflowmax.com/api/workflowmax-api-guide-v1-to-v3

It does not appear to be implemented at present.

**Comment by RettBehrens** [comment]
Hi @LiamTrioTech 

Our OpenAPI specs are used to build our client SDKs which only support JSON requests/responses. Since WorkflowMax currently only supports XML, we won't be adding support for WFM APIs to our client SDKs at this time.

In the meantime, you can use any off the shelf OAuth 2 library to interact with the WorkflowMax API.

NodeJS
https://devblog.xero.com/xero-oauth-2-api-whats-new-node-example-94715fc8ff19
