### ISSUE TITLE
Enabling Oauth2 Client Credentials Flow

### ISSUE THREAD

**Issue by zmaleki** [XeroAPI/xero-node#469]
**SDK you're using (please complete the following information):**
 - Version [3.0.16]

**Is your feature request related to a problem? Please describe.**
Yes, We have an api built in node, the api calls xero-node sdks to calculate everyone's leave and submitted timesheet. If the calculated hours does not match the expected hours it sends a notification in our messaging channel. Our Api were using an older version of xero-node and pem-key to authenticate. With the new updates in the authentication method, now this sdk only allows browser based login through authorisation code grant which we will not be able to use in our api automatic calculation. 

**Describe the solution you'd like**
The feature request is to enable Client Credential Flow in order to authenticate with sdk via headless Apis. Client Credentials is a well known Oauth 2 grant type that is used for server to server accesses. This would enable apis to authenticate via a clientId and a secret

**Comment by RettBehrens** [comment]
Hey @zmaleki for OAuth 2.0 we’ve deliberately chosen to support the code grant type because it is the most suitable grant type for our API access model. All our APIs require an app to act on behalf of a user so it is appropriate that users (resource owners) explicitly grant consent to those apps as part of an authorization flow.

Please see our guide for building [machine-to-machine integrations](https://developer.xero.com/documentation/api-guides/machine-2-machine)

**Comment by teerzo** [comment]
Any updates on this?
https://developer.xero.com/announcements/custom-integrations-are-coming/

**Comment by SerKnight** [comment]
@teerzo this is the official update page for that: https://developer.xero.com/announcements/custom-integrations-are-coming/

Nothing new to report as of today, but know the OA1 deadline for private apps has been extended 3 months from the end of march (end of June)
