### ISSUE TITLE
Multi-Payment Put

### ISSUE THREAD

**Issue by borisno2** [XeroAPI/xero-node#48]
@jordanwalsh23 I have been playing around with Payments this morning and just had a couple of questions happy to put in a PR to solve any of the issues listed:

- Firstly I notice that payments use `createPayment` instead of what seams the standard, and documented `newPayment`, which is preferred? Happy to do a PR to either fix the Docs or bring the payment entity to align with the docs - assuming though `createPayment` might still need to be kept in case people are using it?
- There is no current `savePayments` function to bulk save payments, I have got this working for me, happy to do a PR, probably just need to above question answered first though..

Thanks,
Josh

**Comment by jordanwalsh23** [comment]
I'm happy to have this updated in the 2.2.x release line.  No one has migrated to start using this yet, so we can safely have this as a breaking change for people to upgrade.  

It looks like this is the only instance where it uses the verb `create` instead of `new` so I think it'll be fine to change.

Are you happy to submit a PR?

**Comment by jordanwalsh23** [comment]
Merged PR #49 and deployed xero-node@2.2.1 to resolve this issue.
