### ISSUE TITLE
Why do we have to pass in an array of items when only updating a single item

### ISSUE THREAD

**Issue by adamreisnz** [XeroAPI/xero-node#520]
**SDK you're using (please complete the following information):**
 - Version 4.10.2

**Describe the bug**
I can't be the only one thinking that since the latest version of the SDK, the API's usability and developer friendliness has taken a huge hit.

Consider for example the [`updateInvoice`](https://xeroapi.github.io/xero-node/accounting/index.html#api-Accounting-updateInvoice) route.

![image](https://user-images.githubusercontent.com/490562/114817065-733be280-9e0d-11eb-91eb-726611057df8.png)

As the route implies, we are updating a _single_ invoice.
Why then, do we have to jump around in circles and pass in an _object_ with an _array_ of invoices containing a _single_ invoice?

Where is the sense in this API?

If updating a single item, why can't we just pass in the body of the invoice and be done with it?

This problem affects other routes like updateCreditNotes as well.

This is really cumbersome, ineffective, prone to errors and hard to reason about.

If the API requires the data in this format to consume it, that's fine, but at least the SDK could abstract this away from the developers so that we don't have to worry about those implementation details.

**Comment by SidneyAllen** [comment]
Hi @adamreisnz - Thanks for the feedback.

This issue is more about our OpenAPI specifications, so I've created an issue there so you and other developers can comment or give a thumbs up around the idea along with the implications around it being a breaking change across 6 SDKs.

I'll close this issue and we can carry forward on this issue 😄 
https://github.com/XeroAPI/Xero-OpenAPI/issues/398
