### ISSUE TITLE
getPurchaseOrders call returns empty array if status is not specified

### ISSUE THREAD

**Issue by railz-guli** [XeroAPI/xero-node#527]
**SDK i'm using:**
 - Version 4.11.2

**Bug Description**
Using the SDK, if I make a call to getPurchaseOrders without specifying the purchase order status, instead of returning everything available between the dates specified, it returns nothing.

**To Reproduce**
1. Setup the Xero client and the tenant
2. Once client is setup, make a call to `client.accountingApi.getPurchaseOrders(tenant.tenantId, null, null, '2021-01-01', '2021-04-25', null, 1);`
3. Inspect the `body` object in the response
4. It returns  {"purchaseOrders":[]}.

**Expected behavior**
Instead of returning empty array, it should return every purchase order that has a date between the specified dates.

If I make the call (for the same tenant) with `client.accountingApi.getPurchaseOrders(tenant.tenantId, null)` it works, but the moment I set the `status` null  (ie `client.accountingApi.getPurchaseOrders(tenant.tenantId, null, null)` ) and make the request, it doesn't return the response.

**Comment by SerKnight** [comment]
Hi @railz-guli - I will add this to the docs, but what you want is to set the param as undefined. It's not the most ideal design, and in the long term we will likely move toward a parameter object rather than ordered params.

With parameter as `null` its picking that up as a query `Status=&`
```
http://api-oauth2.xero.com/api.xro/2.0/PurchaseOrders?Status=&DateFrom=2008-01-01&DateTo=2021-04-25&order=&page=1
```
![Screen Shot 2021-07-06 at 3 00 59 PM](https://user-images.githubusercontent.com/2935387/124666240-fc8e0e80-de6a-11eb-8c24-c22e82aad04b.png)

VS parameter as `undefined` it won't look for a specific `null` status.
```
http://api-oauth2.xero.com/api.xro/2.0/PurchaseOrders?DateFrom=2008-01-01&DateTo=2021-04-25&order=&page=1
```
![Screen Shot 2021-07-06 at 3 01 30 PM](https://user-images.githubusercontent.com/2935387/124666286-0e6fb180-de6b-11eb-9d7e-9f4f66d0fc27.png)
