### ISSUE TITLE
Incorrect number of Contacts return from getContacts() with parameter 'IDs'

### ISSUE THREAD

**Issue by neeon-li** [XeroAPI/xero-node#74]
Hi,

Here is my environment
```
Node version: v6.11.1
npm version: v3.10.10
xero-node: v2.5.2
```

Based on [API doc of Contacts](https://developer.xero.com/documentation/api/contacts), the GET method should be able to retrieve a specific set of contacts in a single call with parameter 'IDs'.

So it should be work like this
```
xeroClient.core.contacts.getContacts({
  IDs: "contact-uuid-1,contact-uuid-2"
});
```
But this call return all contacts to me.

So I tried the following call
```
xeroClient.core.contacts.getContacts({
  IDs: [
    "contact-uuid-1",
    "contact-uuid-2"
  ]
});
```
And it still return all the contacts.

**Comment by jordanwalsh23** [comment]
Yes, that's correct. That functionality is not yet supported on the node
SDK.

Feel free to fork/PR.


On 24 Aug. 2017 3:00 pm, "Neeon Li" <notifications@github.com> wrote:

Hi,

Here is my environment

Node version: v6.11.1
npm version: v3.10.10
xero-node: v2.5.2

Based on API doc of Contacts
<https://developer.xero.com/documentation/api/contacts>, the GET method
should be able to retrieve a specific set of contacts in a single call with
parameter 'IDs'.

So it should be work like this

xeroClient.core.contacts.getContacts({
  IDs: "contact-uuid-1,contact-uuid-2"
});

But this call return all contacts to me.

So I tried the following call

xeroClient.core.contacts.getContacts({
  IDs: [
    "contact-uuid-1",
    "contact-uuid-2"
  ]
});

And it still return all the contacts.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/XeroAPI/xero-node/issues/74>, or mute the thread

**Comment by jordanwalsh23** [comment]
I've just added a new test and this actually already works:

```
let contactIDsList = ['id1', 'id2', ...ids];
it('get list of IDs', done => {
    currentApp.core.contacts
      .getContacts({
        params: {
          IDs: contactIDsList.toString()
        }
      })
      .then(contacts => {
        contacts.forEach(contact => {
          expect(contact.ContactID).to.be.oneOf(contactIDsList);
        });
        
        done();
      })
      .catch(err => {
        console.error(util.inspect(err, null, null));
        done(wrapError(err));
      });
  });
```

**Comment by neeon-li** [comment]
Yes ! I tested it and it works.
I really didn't thought about missing `params`.
And thx for updating documents.

Also I really curious that why we need to use `params` ?
Based on [Contacts Docs](https://github.com/XeroAPI/xero-node/blob/038c79aa58bd162b3c0830c0d8bee7728feee697/docs/Contacts.md), the `modifiedAfter`, `order`, `where` and `pager` ([Example in README](https://github.com/XeroAPI/xero-node/blob/038c79aa58bd162b3c0830c0d8bee7728feee697/README.md)) are able to assign directly, but the `IDs`, `ContactIDs`, `InvoiceNumbers` and `Statuses` are under the `params` property.

Does it not inconsistencies with `Optional parameters for GET` [Contacts](https://developer.xero.com/documentation/api/contacts) / [Invoices](https://developer.xero.com/documentation/api/invoices) in API docs ?
Or is there a special reason to do this ?

**Comment by jordanwalsh23** [comment]
To be honest Params is a catch all bucket for any other query parameters
that need to be added.

So you could put a Params object and include 'Where' in there and it would
work also.

I will eventually put another block in there to allow specific use of those
other filters, but Params will also work fine long term.

**Comment by neeon-li** [comment]
I can totally understand that.
Thx.
